version: '3.9'
services:
  worldofgames:
    image: scores_img
    container_name: scores
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:8000"
    volumes:
      - "./src/MainScores.py:/app/src/MainScores.py"
      - "./src/Scores.txt:/app/Scores.txt"
