version: '3.6'

services:
  web:
    container_name: roy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:8000"
    volumes:
      - "./:/app"
    networks:
      - my_app

networks:
  my_app:
    driver: bridge
